# Generated by Django 2.2.1 on 2019-05-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('cover', models.TextField(blank=True, max_length=100000, null=True)),
                ('author', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=25000, null=True)),
                ('available', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(to='category.Category')),
            ],
        ),
    ]
